### PR TITLE
Update package versions to resolve vulnerabilities

### PR DESCRIPTION
**Pull request by jakecyr**
## Overview

Update package versions to resolve most of the ~44 npm audit high vulnerabilities (except for 1) and replace istanbul in favor of the succeeding nyc.

## Testing

Tested by running all unit tests and executing the functions with test data to make sure they return the expected data.

### CODE REVIEW

**Comment by gadicc** [comment]
Thanks, @jakecyr.  This is great!!

@pilwon, LGTM... happy to take care of this if you don't have any comments.

**Comment by jakecyr** [comment]
> Thanks, @jakecyr. This is great!!
> 
> @pilwon, LGTM... happy to take care of this if you don't have any comments.

Happy to help! Let me know if you would like any changes.

**Comment by gadicc** [comment]
Merged and published as v0.3.8 on [npm](https://www.npmjs.com/package/yahoo-finance/v/0.3.8) and [github](https://github.com/pilwon/node-yahoo-finance/releases/tag/v0.3.8).

Thanks so much, @jakecyr... this was a very welcome and high quality PR!

Hope you've also seen some of the work continuing at https://github.com/gadicc/node-yahoo-finance2.

**Comment by jakecyr** [comment]
> published as v0.3

Thank you @gadicc! I'm happy to help. 

I did not, but I'll check that out and would love to contribute more if needed!

**Pull request merged**
