### PR TITLE
[WIP] Yahoo Finance v7 API (since 2017-05-16) - final work (3/3)

### PR DESCRIPTION
**Pull request by gadicc**
**Update**: All the code parts of this PR are merged, released and have been stable for years.  You're welcome to check out work on the [v2 candidate](https://github.com/gadicc/node-yahoo-finance2), in beta probably until mid-2021, at which stage we'll make some official recommendations.

---

Continuation from #37, #41.  Work in Progress.

* [ ] Store cookies, retrieve crumb, cache
  * [ ] Invalidate if cookie has changed
  * [ ] Move `getCrumb()` usage to within `download()`
  * [ ] If called multiple times, queue all requests until `getCrumb()` completes.
* [ ] `quote()`
  * [x] options sanitation
  * [X] Support `symbols` option (i.e. multiple symbols in one request - this needs multiple HTTP requests in yahoo's new API).
  * [ ] tests for shortcut api
* [ ] Add note to README about first request taking longer & why.
* [ ] Do it in one request.  Currently, we send two requests the first time we're run.  But all the data is in the original html result too, we should consider taking it just from there.  Probably not worth doing this as would require multiple parsers for each method.

### CODE REVIEW

**Comment by talbensimon** [comment]
Hi @gadicc / @pilwon - Really looking forward to get the new version that includes the multiple symbols in one request. This is so much needed to avoid breaking my project.

Huge thanks for the awesome work you've been doing :)

**Comment by talbensimon** [comment]
@pilwon I've just tested the recent commit made by @gadicc and both 'quote' and 'historical' are working properly with the long awaited multiple symbols in single query.

**Comment by pilwon** [comment]
@gadicc Do you think multiple symbols feature is good enough to be merged? @talbensimon seems happy with his test results.

**Comment by talbensimon** [comment]
OK, here is an updated list of issues I've discovered so far:
1. For some requests of quote() there is a 404 response which is not handled properly
I get this error in the logs:
Unhandled rejection Error: Failed to download data (404 - {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for ticker symbol: SYMBOL_HERE"}}})

2. On the first run there is an error which doesn't occur afterwards.
Unhandled rejection Error: Failed to get crumb (str.trim is not a function)
at /app/node_modules/yahoo-finance/lib/yahooCrumb.js:72:13

3. There is still the annoying warning upon each call
[yahoo-finance] Warning, Yahoo completely changed their API recently.  quote() replaces the deprecated snapshot(), but is brand new.  Please report any issues.  This notice will be removed in the next release.

Other than that, it's working fine :)
@gadicc @pilwon

**Comment by gadicc** [comment]
Hi @pilwon, @talbensimon.  Sorry for the late reply.  Unfortunately a lot of time sensitive issues have come up for me lately and it will be another week or two until I can look at this again.  From what I recall all the work I did until now was with tests, so if @talbensimon is confirming it works, we could release, and I'll address the other outstanding issues as soon as I can.

**Comment by gadicc** [comment]
@talbensimon, your first issue (about `str.trim`) might be from upgrading an existing install with an older version of tough-cookie.   Try `rm -rf node-modules` and `npm i` (or `yarn install`) again and see if the error goes away.

**Comment by talbensimon** [comment]
Thanks @gadicc, it indeed solved the first issue!

**Comment by damooch** [comment]
Any chance the API is going to come back? I noticed the URL for historical data on yahoo is different than what I'm seeing in the source code. I'm not sure how they are creating their period values.
ex.
5 day period
https://finance.yahoo.com/quote/GOOG/history?period1=1501653600&period2=1502085600&interval=1d&filter=history&frequency=1d

4 day
https://finance.yahoo.com/quote/GOOG/history?period1=1501653600&period2=1501999200&interval=1d&filter=history&frequency=1d

where period 2 has changed:
     8/7/17		  8/6/17
1502085600           1501999200

**Comment by damooch** [comment]
You guys are doing awesome. I found a cool url if you want to take a look at it.
https://query1.finance.yahoo.com/v8/finance/chart/GOOG?range=1d&includePrePost=false&interval=2m&corsDomain=finance.yahoo.com&.trsc=finance

**Comment by milesalex** [comment]
Cheering everyone on in this PR!

**Comment by aryehbeitz** [comment]
I created a working version which pulls google and yahoo stock data.
https://github.com/aryehbeitz/BaseNodeRoutes
There's a live server running too - all a work in progress so don't use for production

**Comment by MichaelWhite63** [comment]
Reading through the comments it reads as if the code has been amended to handle Yahoo's changes.  Is that correct?  Will 'npm install --save yahoo-finance' give me the correct version?

**Comment by Luchanso** [comment]
Please, can you merge multiply symbol? Better in future create merge request for every new feature

**Comment by pilwon** [comment]
@Luchanso Please check out @gadicc's PR #47.

**Comment by gadicc** [comment]
Yeah, all, pilwon just merged PR #47 and published as v0.3.3 - that's all my work on this from earlier this year.  I still wanted to leave this PR open to track the rest of the changes, which in my mind are still critical for this to be considered "finished".  And as per earlier comment, I do regret how some big unexpected commitments totally halted my work on this until now.  Still hoping to try to finish this off as soon as I can.

**Comment by GuilhermeZaniniMoreira** [comment]
How do I use it with ES2015?

**Comment by gadicc** [comment]
Hi @GuilhermeZaniniMoreira 

If you don't pass `historical()` or `quote()` a callback as the final parameter, they'll return a promise, which can be used with ES2017 async/await (is that what you meant?).

There are some examples in the [full quote docs](https://github.com/pilwon/node-yahoo-finance/blob/master/docs/quote.md), which includes a convenient shortcut API, e.g.

```js
const result = await quote('TSLA');  // implies default modules below
const result = await quote('TSLA', ['summaryDetail', 'recommendationTrend']);
```

or as just a regular promise:

```js
quote('TSLA').then(function(data) { console.log(data); });
```

**Comment by stuckinaboot** [comment]
Is this still being worked on?

**Comment by gadicc** [comment]
@stuckinaboot, @pilwon - I regret I never got to finish this exactly how I wanted, however, I may have been a bit too pedantic, as even without the extra resiliency I'd planned, all the previously submitted code has continued to work great for years.

@pilwon, I've just made some changes to the README to cleanup the notices and add a bit a note about the first request taking longer.  I think let's merge and close?

**Comment by DDeme** [comment]
When it will be merged  ?

**Comment by gadicc** [comment]
@DDeme do note that the only part left of this PR that hasn't been merged yet are some updates to the README, all the code is already in the released version.

**Comment by DDeme** [comment]
Great do you have any plans to migrate to typescript?

**Comment by gadicc** [comment]
Sure, why not, that's a good idea.  It will be my first time using typescript :sweat_smile:

**Comment by gadicc** [comment]
@DDeme, re typescript, see https://github.com/pilwon/node-yahoo-finance/issues/75#issuecomment-771587499.

**Comment by kuworking** [comment]
Great that the merge seems very close, what version should we wait for?

**Comment by gadicc** [comment]
Hey @kuworking, it's only really some changes to the README we still have to do, all the code parts have been merged already and have been stable for years :sweat_smile: 

You're welcome to also check out the work happening at [node-yahoo-finance2](https://github.com/gadicc/node-yahoo-finance2) although I think we'll keep that in beta for 3-6 months before making any official recommendations.

**Comment by kuworking** [comment]
Then thanks god I've asked, I could have been waiting for years 🤓

What's the difference between the two? Is it a major rewriting? And thanks a lot for this development, I'm gonna try it right now 🙌

**Comment by gadicc** [comment]
:laughing: 

Yes, exactly.  The v2 candidate is a complete rewrite from scratch, whereas the current version has been stable for years.  So we'll keep it in beta for some time before making any official recommendations.

**Comment by gadicc** [comment]
I made an update at the top of the this post for clarity and I'll hope we'll merge the rest soon.

**Comment by darren-outdev** [comment]
> Sure, why not, that's a good idea. It will be my first time using typescript 😅

Need some assistance?

**Comment by gadicc** [comment]
Hey @darren-outdev, thanks.  Did you mean assistance with TypeScript or in general?

In any case, both are very welcome.  See where we're at at https://github.com/gadicc/node-yahoo-finance2.

In general: we just need help testing the library (which is in beta now).
Re typescript: I think I got up to speed quick but please let me know if you notice anything wrong or unconventional.

Thanks!

**Comment by darren-outdev** [comment]
Oh wow, you've gotten far! Well done :) Yeah I meant specifically with TS, been using it for years. I'll browse around the linked project and use the standard contributions method if I have updates

**Comment by gadicc** [comment]
Thanks and thanks, @darren-outdev!  That would be awesome :grin:

**Comment by pilwon** [comment]
Merged and published as v0.3.7.

@gadicc Sorry for not checking & merging your changes earlier. I meant to do a TS rewrite for years but it never happened. I have just invited you as collaborator to this repo and also added you as owner for `yahoo-finance` npm package. Once your TS version development is completed, please consider publishing to `yahoo-finance` as new major version since having two repos could confuse people. We can either merge two repos or archive this one.

**Comment by gadicc** [comment]
Thanks, @pilwon! :grinning:

**Pull request merged**
