### PR TITLE
Yahoo Finance v7 API (since 2017-05-16) - finish snapshot()

### PR DESCRIPTION
**Pull request by gadicc**
Continuation from #37 for `snapshot()`.

* [X] `snapshot()`
  * [x] Convert old API field options
  * [x] Support `symbols` option (i.e. multiple symbols in one request - this needs multiple HTTP requests in yahoo's new API).
  * [x] Ensure output is consistent with earlier API
  * [x] convert dates

### CODE REVIEW

**Comment by gadicc** [comment]
@pilwon, ok, changed my mind :)  This PR is just for `snapshot()`.  Sorry, I just saw all your references to this issue but your earlier comments about shipping as early as possible have been stuck in my mind and I think this is ready to ship and might help some people.

Take a look through the changes and please try any of your own tests if you have any.  You can ignore my merge messages in the commits and just squash everything.  Everything else really should be in one final PR, which is less time sensitive.  I'll update all the other threads with links when I open it.

**Comment by gadicc** [comment]
oh actually just wait one sec, sorry.

**Comment by gadicc** [comment]
Ok I just rebased on my end down to 5 sensible commits, which I think you can merge now without squashing.  It's a lot clearer to have i.e. file splits and unrelated changes in their own commits.

**Comment by pilwon** [comment]
@gadicc Awesome! 👍 👍 👍

**Pull request merged**
